jobs:
 - name: u14javall-test
   type: runSh
   steps:
    - IN: u14all-testing
     - TASK:
         runtime:
           options:
             imageName: "drydock/u14javall"
             imageTag: master
         script:
           - shipctl jdk set openjdk7
           - shipctl jdk set openjdk8
           - shipctl jdk set oraclejdk8
           - shipctl jdk set oraclejdk10
           - mvn --version
           - ant -version
           - gradle --version
